//
//  UIColor+LottieColors.h
//
//  Generated by Zeplin on 4/10/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

#import <UIKit/UIKit.h>

@interface UIColor (LottieColors)

+ (UIColor *)deepSkyBlueColor;
+ (UIColor *)sapGreenColor;

@end
