//
//  UIColor+LottieColors.m
//
//  Generated by Zeplin on 4/10/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

#import "UIColor+LottieColors.h"

@implementation UIColor (LottieColors)

+ (UIColor *)deepSkyBlueColor {
	return [UIColor colorWithRed:3.0f / 255.0f green:120.0f / 255.0f blue:251.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)sapGreenColor {
	return [UIColor colorWithRed:50.0f / 255.0f green:207.0f / 255.0f blue:193.0f / 255.0f alpha:1.0f];
}

@end
